export const SEQUELIZE = 'SEQUELIZE'
export const DEVELOPMENT = 'development'
export const TEST = 'test'
export const PRODUCTION = 'production'
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY'
export const ANSWER_REPOSITORY = 'ANSWER_REPOSITORY'
export const QUIZ_REPOSITORY = 'QUIZ_REPOSITORY'
