export const main = [
  "import { NestFactory } from '@nestjs/core';",
  "import { AppModule } from './app.module';",
  '',
  'async function bootstrap() {',
  '  const app = await NestFactory.create(AppModule);',
  '  await app.listen(3000);',
  '}',
  'bootstrap();',
].join('\n')

export const app_module = [
  "import { Module } from '@nestjs/common';",
  "import { AppController } from './app.controller';",
  "import { AppService } from './app.service';",
  '',
  '@Module({',
  '  imports: [],',
  '  controllers: [AppController],',
  '  providers: [AppService],',
  '})',
  'export class AppModule {}',
].join('\n')

export const app_controller = [
  "import { Controller, Get } from '@nestjs/common';",
  "import { AppService } from './app.service';",
  '',
  '@Controller()',
  'export class AppController {',
  '  constructor(private readonly appService: AppService) {}',
  '',
  '  @Get()',
  '  getHello(): string {',
  '    return this.appService.getHello();',
  '  }',
  '}',
].join('\n')

export const app_service = [
  "import { Injectable } from '@nestjs/common';",
  '',
  '@Injectable()',
  'export class AppService {',
  '  getHello(): string {',
  "    return 'Hello World!';",
  '  }',
  '}',
].join('\n')

export const app_controller_spec = [
  "import { Test, TestingModule } from '@nestjs/testing';",
  "import { AppController } from './app.controller';",
  "import { AppService } from './app.service';",
  '',
  "describe('AppController', () => {",
  '  let appController: AppController;',
  '',
  '  beforeEach(async () => {',
  '    const app: TestingModule = await Test.createTestingModule({',
  '      controllers: [AppController],',
  '      providers: [AppService],',
  '    }).compile();',
  '',
  '    appController = app.get<AppController>(AppController);',
  '  });',
  '',
  "  describe('root', () => {",
  '    it(\'should return "Hello World!"\', () => {',
  "      expect(appController.getHello()).toBe('Hello World!');",
  '    });',
  '  });',
  '});',
].join('\n')

export const app_e2e_spec = [
  "import { Test, TestingModule } from '@nestjs/testing';",
  "import { INestApplication } from '@nestjs/common';",
  "import request from 'supertest';",
  "import { AppModule } from './../src/app.module';",
  '',
  "describe('AppController (e2e)', () => {",
  '  let app: INestApplication;',
  '',
  '  beforeEach(async () => {',
  '    const moduleFixture: TestingModule = await Test.createTestingModule({',
  '      imports: [AppModule],',
  '    }).compile();',
  '',
  '    app = moduleFixture.createNestApplication();',
  '    await app.init();',
  '  });',
  '',
  "  it('/ (GET)', () => {",
  '    return request(app.getHttpServer())',
  "      .get('/')",
  '      .expect(200)',
  "      .expect('Hello World!');",
  '  });',
  '});',
].join('\n')

export const jest_e2e_json = [
  '{',
  '  "moduleFileExtensions": ["js", "json", "ts"],',
  '  "rootDir": ".",',
  '  "testEnvironment": "node",',
  '  "testRegex": ".e2e-spec.ts$",',
  '  "transform": {',
  '    "^.+\\\\.(t|j)s$": "ts-jest"',
  '  }',
  '}',
  '',
].join('\n')
